encoding: utf-8
name: Arshika Lalan
url: https://arshika77.github.io
author:
  name: Arshika Lalan
  email: arshika77@gmail.com
description: Pre-Doctoral Researcher at Google AI.
permalink: /posts/:title/
include: ['_pages']
