encoding: utf-8
name: Arshika Lalan
url: https://arshika77.github.io
author:
  name: Arshika Lalan
  email: arshika77@gmail.com
description: Masters of Science in Machine Learning at Carnegie Mellon University
permalink: /posts/:title/
include: ['_pages']
